# Generated by Django 5.1.4 on 2026-05-13 06:27

import django.db.models.deletion
import systemapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesheet_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('procurement_status', models.CharField(choices=[('NORMAL', 'Normal Notesheet'), ('PURCHASE_PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATION_ENTRY', 'Quotation Entry'), ('QUOTATION_PENDING_CHAIRMAN', 'Quotation Pending Chairman'), ('VENDOR_SELECTION', 'Vendor Selection'), ('FINAL_PENDING_CHAIRMAN', 'Final Chairman Approval'), ('PO_GENERATED', 'PO Generated'), ('FINANCE_PENDING', 'Pending Finance Approval'), ('PAYMENT_DONE', 'Payment Done'), ('INVENTORY_ENTRY', 'Inventory Entry'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent Back')], default='NOT_STARTED', max_length=50)),
                ('previous_procurement_status', models.CharField(blank=True, choices=[('NORMAL', 'Normal Notesheet'), ('PURCHASE_PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATION_ENTRY', 'Quotation Entry'), ('QUOTATION_PENDING_CHAIRMAN', 'Quotation Pending Chairman'), ('VENDOR_SELECTION', 'Vendor Selection'), ('FINAL_PENDING_CHAIRMAN', 'Final Chairman Approval'), ('PO_GENERATED', 'PO Generated'), ('FINANCE_PENDING', 'Pending Finance Approval'), ('PAYMENT_DONE', 'Payment Done'), ('INVENTORY_ENTRY', 'Inventory Entry'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent Back')], default='', max_length=50)),
                ('purchase_order_no', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('purchase_order_file', models.FileField(blank=True, null=True, upload_to='notesheets/purchase_orders/', validators=[systemapp.models.validate_note_attachment])),
                ('stock_register_details', models.TextField(blank=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_entry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notesheets', to='userapp.user')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systemapp.department')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notesheets', to='userapp.user')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemapp.purpose')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('COMMENT', 'Comment'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERT', 'Revert Back'), ('FORWARDED', 'Forwarded')], max_length=20)),
                ('remark_text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notesheets/remarks/', validators=[systemapp.models.validate_note_attachment])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_given', to='userapp.user')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks_received', to='userapp.user')),
                ('visible_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visible_remarks', to='userapp.user')),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='systemapp.notesheet')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notesheets/', validators=[systemapp.models.validate_note_attachment])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='systemapp.notesheet')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True)),
                ('notesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='systemapp.notesheet')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='notesheets/quotations/', validators=[systemapp.models.validate_note_attachment])),
                ('is_l1', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='systemapp.notesheet')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_quotations', to='userapp.user')),
            ],
            options={
                'ordering': ['amount', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_price', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='notesheets/quotations/', validators=[systemapp.models.validate_note_attachment])),
                ('address', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='systemapp.notesheet')),
            ],
        ),
    ]
