# Generated by Django 5.1.4 on 2026-04-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesheet_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notesheets', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notesheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERT', 'Revert Back'), ('FORWARDED', 'Forwarded')], max_length=20)),
                ('remark_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks_received', to=settings.AUTH_USER_MODEL)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='systemapp.notesheet')),
            ],
        ),
        migrations.CreateModel(
            name='NoteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notesheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='systemapp.notesheet')),
            ],
        ),
        migrations.CreateModel(
            name='NoteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('notesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='systemapp.notesheet')),
            ],
        ),
    ]
