# Generated by Django 6.0.5 on 2026-06-01 08:30

import django.db.models.deletion
import systemapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesheet_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('procurement_status', models.CharField(choices=[('NORMAL', 'Normal'), ('PURCHASE_PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATION_ENTRY', 'Quotation Entry'), ('QUOTATION_PENDING_CHAIRMAN', 'Quotation Pending Chairman'), ('QUOTATION_REVERTED', 'Quotation Reverted'), ('PO_PENDING', 'PO Pending'), ('PO_GENERATED', 'PO Generated'), ('INVENTORY_ENTRY', 'Inventory Entry'), ('FINANCE_REVIEW', 'Finance Review'), ('BILL_PENDING_CHAIRMAN', 'Bill Pending Chairman'), ('FINAL_FINANCE_APPROVAL', 'Final Finance Approval'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=50)),
                ('previous_procurement_status', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('PURCHASE_PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATION_ENTRY', 'Quotation Entry'), ('QUOTATION_PENDING_CHAIRMAN', 'Quotation Pending Chairman'), ('QUOTATION_REVERTED', 'Quotation Reverted'), ('PO_PENDING', 'PO Pending'), ('PO_GENERATED', 'PO Generated'), ('INVENTORY_ENTRY', 'Inventory Entry'), ('FINANCE_REVIEW', 'Finance Review'), ('BILL_PENDING_CHAIRMAN', 'Bill Pending Chairman'), ('FINAL_FINANCE_APPROVAL', 'Final Finance Approval'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='', max_length=50)),
                ('purchase_order_no', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('purchase_order_file', models.FileField(blank=True, null=True, upload_to='notesheets/purchase_orders/', validators=[systemapp.models.validate_note_attachment])),
                ('stock_register_details', models.TextField(blank=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_entry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po_pdf', models.FileField(blank=True, null=True, upload_to='purchase_orders/')),
                ('finance_attachment', models.FileField(blank=True, null=True, upload_to='notesheets/finance_attachments/')),
                ('collage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systemapp.collage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notesheets', to='userapp.user')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systemapp.department')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notesheets', to='userapp.user')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemapp.purpose')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('COMMENT', 'Comment'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERT', 'Revert Back'), ('FORWARDED', 'Forwarded')], max_length=20)),
                ('remark_text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notesheets/remarks/', validators=[systemapp.models.validate_note_attachment])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_given', to='userapp.user')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks_received', to='userapp.user')),
                ('visible_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visible_remarks', to='userapp.user')),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='systemapp.notesheet')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('added_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systemapp.notesheet')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_file', models.FileField(upload_to='purchase_orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
                ('notesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='systemapp.notesheet')),
            ],
        ),
    ]