# Generated by Django 5.1.4 on 2026-04-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteremark',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_given', to='userapp.user'),
        ),
        migrations.AlterField(
            model_name='noteremark',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks_received', to='userapp.user'),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notesheets', to='userapp.user'),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='forwarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notesheets', to='userapp.user'),
        ),
    ]
