# Generated by Django 6.0.5 on 2026-06-01 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='notesheets/quotations/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='systemapp.notesheet')),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quotation_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='systemapp.vendorquotation')),
            ],
        ),
    ]
