# Generated by Django 5.1.4 on 2026-05-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notedocument',
            name='notesheet',
        ),
        migrations.RemoveField(
            model_name='procurementquotation',
            name='notesheet',
        ),
        migrations.RemoveField(
            model_name='procurementquotation',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='collage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systemapp.collage'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemapp.quotationitem')),
            ],
        ),
        migrations.DeleteModel(
            name='NoteContent',
        ),
        migrations.DeleteModel(
            name='NoteDocument',
        ),
        migrations.DeleteModel(
            name='ProcurementQuotation',
        ),
    ]
