# Generated by Django 6.0.5 on 2026-06-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0002_vendorquotation_vendorquotationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='systemapp.vendorquotation'),
        ),
    ]
