# Generated by Django 5.1.4 on 2026-05-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0002_collage_remove_notedocument_notesheet_and_more'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheet',
            name='previous_procurement_status',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('PURCHASE_PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATION_ENTRY', 'Quotation Entry'), ('QUOTATION_PENDING_CHAIRMAN', 'Quotation Pending Chairman'), ('QUOTATION_REVERTED', 'Quotation Reverted'), ('PO_PENDING', 'PO Pending'), ('PO_GENERATED', 'PO Generated'), ('INVENTORY_ENTRY', 'Inventory Entry'), ('FINANCE_REVIEW', 'Finance Review'), ('BILL_PENDING_CHAIRMAN', 'Bill Pending Chairman'), ('FINAL_FINANCE_APPROVAL', 'Final Finance Approval'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='procurement_status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PURCHASE_PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATION_ENTRY', 'Quotation Entry'), ('QUOTATION_PENDING_CHAIRMAN', 'Quotation Pending Chairman'), ('QUOTATION_REVERTED', 'Quotation Reverted'), ('PO_PENDING', 'PO Pending'), ('PO_GENERATED', 'PO Generated'), ('INVENTORY_ENTRY', 'Inventory Entry'), ('FINANCE_REVIEW', 'Finance Review'), ('BILL_PENDING_CHAIRMAN', 'Bill Pending Chairman'), ('FINAL_FINANCE_APPROVAL', 'Final Finance Approval'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=50),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_file', models.FileField(upload_to='purchase_orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
                ('notesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='systemapp.notesheet')),
            ],
        ),
    ]
