# Generated by Django 5.1.4 on 2026-04-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0002_alter_noteremark_from_user_alter_noteremark_to_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteremark',
            old_name='from_user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='noteremark',
            old_name='to_user',
            new_name='forwarded_to',
        ),
    ]
