# Generated by Django 5.1.4 on 2026-04-28 09:59

import systemapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0003_rename_from_user_noteremark_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedocument',
            name='file',
            field=models.FileField(upload_to='notesheets/', validators=[systemapp.models.validate_pdf]),
        ),
    ]
