# Generated by Django 6.0.5 on 2026-06-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0003_remove_purchaseorder_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='general_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='pending', max_length=50),
        ),
    ]
