# Generated by Django 5.1.4 on 2026-05-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0003_alter_notesheet_previous_procurement_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
