# Generated by Django 5.1.4 on 2026-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0004_alter_quotationitem_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_pdf',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
    ]
