# Generated by Django 6.0.5 on 2026-06-02 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0004_notesheet_general_status'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.user'),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='general_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
    ]
