# Generated by Django 5.1.4 on 2026-05-02 10:21

import systemapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0005_department_notesheet_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notedocument',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='noteremark',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='notesheet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notecontent',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notedocument',
            name='file',
            field=models.FileField(upload_to='notesheets/', validators=[systemapp.models.validate_note_attachment]),
        ),
        migrations.AlterField(
            model_name='noteremark',
            name='action',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERT', 'Revert Back'), ('FORWARDED', 'Forwarded')], max_length=20),
        ),
    ]
