# Generated by Django 6.0.5 on 2026-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0005_notesheet_approved_by_alter_notesheet_general_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='collage_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
