# Generated by Django 5.1.4 on 2026-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0005_purchaseorder_po_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_pdf',
        ),
        migrations.AddField(
            model_name='notesheet',
            name='po_pdf',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
    ]
