# Generated by Django 4.2.23 on 2026-06-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0006_collage_collage_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
