# Generated by Django 5.1.4 on 2026-05-02 13:01

import systemapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0006_alter_notedocument_options_alter_noteremark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteremark',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notesheets/remarks/', validators=[systemapp.models.validate_note_attachment]),
        ),
    ]
