# Generated by Django 5.1.4 on 2026-05-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0006_remove_purchaseorder_po_pdf_notesheet_po_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='is_l1',
            field=models.BooleanField(default=False),
        ),
    ]
