# Generated by Django 5.1.4 on 2026-05-02 15:44

import django.db.models.deletion
import systemapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0007_noteremark_attachment'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='previous_procurement_status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'Not Started'), ('PENDING_DIRECTOR', 'Pending Director'), ('PENDING_CHAIRMAN', 'Pending Chairman'), ('QUOTATIONS_UPLOAD', 'Quotations Upload'), ('PENDING_L1_APPROVAL', 'Pending L1 Approval'), ('PO_GENERATION', 'PO Generation'), ('ORDER_PLACED', 'Order Placed'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_DONE', 'Payment Done'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='procurement_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING_DIRECTOR', 'Pending Director'), ('PENDING_CHAIRMAN', 'Pending Chairman'), ('QUOTATIONS_UPLOAD', 'Quotations Upload'), ('PENDING_L1_APPROVAL', 'Pending L1 Approval'), ('PO_GENERATION', 'PO Generation'), ('ORDER_PLACED', 'Order Placed'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_DONE', 'Payment Done'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='purchase_order_file',
            field=models.FileField(blank=True, null=True, upload_to='notesheets/purchase_orders/', validators=[systemapp.models.validate_note_attachment]),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='stock_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='stock_register_details',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProcurementQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='notesheets/quotations/', validators=[systemapp.models.validate_note_attachment])),
                ('is_l1', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='systemapp.notesheet')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_quotations', to='userapp.user')),
            ],
            options={
                'ordering': ['amount', 'created_at'],
            },
        ),
    ]
