# Generated by Django 5.1.4 on 2026-05-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0007_quotationitem_is_l1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='added_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
