# Generated by Django 5.1.4 on 2026-05-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0008_notesheet_previous_procurement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='purchase_order_no',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
