# Generated by Django 5.1.4 on 2026-05-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0008_alter_inventoryitem_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
