# Generated by Django 5.1.4 on 2026-05-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0009_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='quote_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
