# Generated by Django 5.1.4 on 2026-05-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0010_purpose_notesheet_purpose'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='previous_procurement_status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'Not Started'), ('PENDING_APPROVAL', 'Pending Approval'), ('PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATIONS_UPLOAD', 'Quotations Upload'), ('VENDOR_UPLOAD', 'Vendor Details Upload'), ('PENDING_FINAL_APPROVAL', 'Pending Final Approval'), ('PO_GENERATION', 'PO Generation'), ('ORDER_PLACED', 'Order Placed'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_DONE', 'Payment Done'), ('STOCK_REGISTER', 'Stock Register Entry'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='procurement_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING_APPROVAL', 'Pending Approval'), ('PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATIONS_UPLOAD', 'Quotations Upload'), ('VENDOR_UPLOAD', 'Vendor Details Upload'), ('PENDING_FINAL_APPROVAL', 'Pending Final Approval'), ('PO_GENERATION', 'PO Generation'), ('ORDER_PLACED', 'Order Placed'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_DONE', 'Payment Done'), ('STOCK_REGISTER', 'Stock Register Entry'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemapp.purpose'),
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='systemapp.procurementquotation')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=50)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_detail', to='systemapp.notesheet')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details_uploaded', to='userapp.user')),
            ],
        ),
    ]
