# Generated by Django 5.1.4 on 2026-05-07 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0011_remove_purpose_created_at_remove_purpose_is_deleted_and_more'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteremark',
            name='visible_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visible_remarks', to='userapp.user'),
        ),
    ]
