# Generated by Django 5.1.4 on 2026-05-07 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0013_remove_noteremark_visible_to_and_more'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteremark',
            name='visible_users',
        ),
        migrations.AddField(
            model_name='noteremark',
            name='visible_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visible_remarks', to='userapp.user'),
        ),
    ]
