# Generated by Django 5.1.4 on 2026-05-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0014_remove_noteremark_visible_users_and_more'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteremark',
            name='visible_to',
        ),
        migrations.AddField(
            model_name='noteremark',
            name='visible_users',
            field=models.ManyToManyField(blank=True, related_name='visible_remarks', to='userapp.user'),
        ),
    ]
