# Generated by Django 5.1.4 on 2026-05-08 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0016_remove_noteremark_visible_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='vendordetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendordetail',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='vendordetail',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='vendordetail',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='vendordetail',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='notesheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='systemapp.notesheet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='previous_procurement_status',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal Notesheet'), ('PURCHASE_PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATION_ENTRY', 'Quotation Entry'), ('QUOTATION_PENDING_CHAIRMAN', 'Quotation Pending Chairman'), ('VENDOR_SELECTION', 'Vendor Selection'), ('FINAL_PENDING_CHAIRMAN', 'Final Chairman Approval'), ('PO_GENERATED', 'PO Generated'), ('FINANCE_PENDING', 'Pending Finance Approval'), ('PAYMENT_DONE', 'Payment Done'), ('INVENTORY_ENTRY', 'Inventory Entry'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent Back')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='procurement_status',
            field=models.CharField(choices=[('NORMAL', 'Normal Notesheet'), ('PURCHASE_PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('QUOTATION_ENTRY', 'Quotation Entry'), ('QUOTATION_PENDING_CHAIRMAN', 'Quotation Pending Chairman'), ('VENDOR_SELECTION', 'Vendor Selection'), ('FINAL_PENDING_CHAIRMAN', 'Final Chairman Approval'), ('PO_GENERATED', 'PO Generated'), ('FINANCE_PENDING', 'Pending Finance Approval'), ('PAYMENT_DONE', 'Payment Done'), ('INVENTORY_ENTRY', 'Inventory Entry'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent Back')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendordetail',
            name='gst_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendordetail',
            name='notesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemapp.notesheet'),
        ),
        migrations.AlterField(
            model_name='vendordetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='InventoryRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_name', models.CharField(max_length=255)),
                ('stock_entry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemapp.notesheet')),
            ],
        ),
    ]
