# Generated by Django 5.1.4 on 2026-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0017_remove_quotationitem_quotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetail',
            name='quote_price',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendordetail',
            name='unit_price',
            field=models.CharField(blank=True, null=True),
        ),
    ]
